lancerJeu()
let inputEcriture=document.getElementById("inputEcriture")
console.log(inputEcriture)
let btnValiderMot=document.getElementById("btnValiderMot")
console.log(btnValiderMot)
let divZoneProposition=document.querySelector(".zoneProposition")
console.log(MotAffiché)
let spanScore=document.querySelector(".zoneScore")
console.log(spanScore)
let BoutonRadioChoix=document.querySelectorAll(".zoneOptions radio")