lancerJeu()
let inputEcriture=document.getElementById("inputEcriture")
console.log(inputEcriture)
let btnValiderMot=document.getElementById("btnValiderMot")
console.log(btnValiderMot)
let divZoneProposition=document.querySelector(".zoneProposition")
console.log(divZoneProposition)
let spanScore=document.querySelector(".zoneScore")
console.log(spanScore)
let listeBtnRadio=document.querySelectorAll(".optionsource radio")
